### ISSUE TITLE
Please Add Regular Checkout (URL) Payment System.

### ISSUE THREAD

**Issue by torikulislamrijon** [kapilpaul/bKash-woocommerce#14]
Please Add Regular Checkout (URL) Payment System.

Checkout url is not working on your plugin 

Create Payment API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/create

Execute Payment API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/execute

Grant Token API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/token/grant

Query Payment API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/payment/status

Refresh Token API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/token/refresh

Refund API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/payment/refund

Refund Status API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/payment/refund

Search Transaction API

Endpoint:https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/general/searchTransaction

**Comment by kapilpaul** [comment]
It's already added in the plugin.Thanks
