### ISSUE TITLE
No Generate Doc option

### ISSUE THREAD

**Issue by mmshaifur** [kapilpaul/bKash-woocommerce#18]
The plug does not show Generate Doc anymore. 
I am using the latest version of wordpress and woocommerce.

Thank you.
![no-generate-doc](https://github.com/kapilpaul/bKash-woocommerce/assets/9750061/1c72e5c9-972e-4688-a8fa-53a345a8d5cc)

**Comment by kapilpaul** [comment]
Hi the doc generation is not needed anymore.
thanks
