### ISSUE TITLE
Bkash Requires additional things now to activate gateway now

### ISSUE THREAD

**Issue by kokilkhan24** [kapilpaul/bKash-woocommerce#4]
Your plugin is excellent. Really I like it. I test it with Sandbox successfully. After sanbox testing, Bkash told us now 2nd Sandbox testing to validate the payment gateway. They told me to provide these things in email. Can you tell me please how can I get all of this API Title, API URL, Request Body, API Response and Error Code Implementation?

**********************************

Please share formal sandbox test request of each below APIs in text format so that we can validate –
Grant Token : https://developer.bka.sh/v1.2.0-beta/reference#gettokenusingpost
Create Payment : https://developer.bka.sh/v1.2.0-beta/reference#createpaymentusingpost
Execute Payment : https://developer.bka.sh/v1.2.0-beta/reference#executepaymentusingpost
Query Payment : https://developer.bka.sh/v1.2.0-beta/reference#querypaymentusingget (Mandatory)
Search Transaction Details : https://developer.bka.sh/v1.2.0-beta/reference#searchtransactionusingget
Refund Transaction : https://developer.bka.sh/docs/refund-transaction
Refund Status : https://developer.bka.sh/docs/refund-status

Note: please use the same payment ID to call Create, Execute and Query payment API

Please maintain following format to share the responses using 2nd sandbox credential –
• API Title :
• API URL :
• Request Body :
• API Response :
Error Code Implementation :

You have to implement all the error messages according to the error codes (https://developer.bka.sh/docs/error-codes ) so that customer gets a clear message and perform following tasks for validation –
a. You have to perform two transactions within 2min duration, with the same amount. In 2nd transaction you will get an error message.
b. You need to initiate a transaction and put wrong/invalid OTP three times deliberately. In response you will get an error message.

After performing the above two tasks please share the following for both tasks –
1. Invoice number of each transaction.
2. Payment ID of each transaction.
3. Timestamp of each transaction.
4. Screenshot of error messages.

**********************************

**Comment by kapilpaul** [comment]
thanks for mentioned this. I will take care of everything in the next release. Hopefully, you will enjoy it.

**Comment by kokilkhan24** [comment]
Thank you your reply :) 

I sent you an email in your kapilpaul007@gmail.com email with a sample file "PGW Checkout (iFrame) API Response Sample" which I get from Bkash. Can you please check your gmail for more details?
